### ISSUE TITLE
你好，请问下在windows下如何编译成dll文件？

### ISSUE THREAD

**Issue by DefconZhou** [cundong/SmartAppUpdates#4]
按照jni的几个步骤都很顺利，最后一步在编译成dll文件时，报以下错误。应该是C代码中使用linux系统库的原因。麻烦问下，你这边是如何编译的？而且在项目中也没有看到dll文件。是不是使用cygwin类似的编译器来编译的？
![qq 20150311135436](https://cloud.githubusercontent.com/assets/2505581/6591134/f1689e86-c7f5-11e4-8f39-41234ead9415.jpg)

**Comment by DefconZhou** [comment]
刚才测试了利用cygwin进行编译。报以下错误。
![qq 20150311145813](https://cloud.githubusercontent.com/assets/2505581/6591723/d83c924c-c7fe-11e4-8c74-79524fd87784.jpg)

**Comment by DefconZhou** [comment]
已经在window下利用cygwin编译成功，替换了linuxx64下的jdk

**Comment by Ivolian** [comment]
@DefconZhou  想请教下如何使用 cygwin 编译 dll，已经安装了 cygwin 和 gcc。

**Comment by cundong** [comment]
@DefconZhou 建议你把你的方法分享给 @Ivolian 
替他谢谢你啦。

**Comment by DefconZhou** [comment]
@Ivolian @cundong 
cygwin下编译dll最后虽然成功了，但是无法正常使用的。编译成功好像把我上面的cygwin编译命令上include windows jdk路径 改为 cygwin中的linux jdk 路径。 
最终我还是在Ubuntu下面成功编译和使用的。windows虽然编译成功，但是无法正常使用。
