### ISSUE TITLE
ApkPatchLibrary使用ndk-build构建时报错

### ISSUE THREAD

**Issue by heyanyanchina123** [cundong/SmartAppUpdates#5]
环境android-ndk-r10e，jni/com_cundong_utils_PatchUtils.c:60: error: undefined reference to 'errx'

**Comment by cundong** [comment]
这个问题是因为你的编译环境标准库IO中没有errx()函数，如果你是在Window环境，建议你使用cygwin

**Comment by Ivolian** [comment]
@cundong  
我需要帮助。
之前有过使用 so 的经验，但生成 dll 让我束手无策。
能指点一下吗。
![default](https://cloud.githubusercontent.com/assets/7471905/11953734/55fa72ca-a8dd-11e5-9ccc-b467f9d33095.PNG)

**Comment by cundong** [comment]
我给你几个参考配置的文档哈


http://blog.csdn.net/binyao02123202/article/details/18075747

http://www.bogotobogo.com/cplusplus/eclipse_CDT_JNI_MinGW_64bit.php

http://blog.csdn.net/yanzi1225627/article/details/18891613

**Comment by Ivolian** [comment]
@cundong 
都是 eclipse 的介绍，我只用过 intellij 和 androidstudio。。。
我用 ndk 编译 ApkPatchLibrary 下 PatchUtils.c 是通过的，生成的 so 可以正常合并分差包。

但再编译 ApkPatchLibraryServer 中 PatchUtils.c 或 DiffUtils.c 时会出现和上面使用 cynwin gcc 一样的错误：

**Comment by kjsolo** [comment]
请问我的是Mac上的编译的，也是报这个错误，该如何配置？
