### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by jayronlou** [cundong/SmartAppUpdates#7]
这个增量升级方案在4.1以下的版本不能用？

**Comment by cundong** [comment]
当然可以用。

**Comment by jayronlou** [comment]
但是微博apk在4.0的手机上根本装不上去，安装的时候报错：INSTALL_FAILED_OLDER_SDK

**Comment by cundong** [comment]
额，，这跟SmartAppUpdates有什么关系呢。。

**Comment by jayronlou** [comment]
好吧，我还以为在4.1以下的版本不能用呢，我试下，多谢了

**Comment by cundong** [comment]
可能你误解了哈

从4.1开始，Google Play 这个应用使用了增量更新这个机制，但是这不代表4.1之前这个机制其他APP不能用。

2016-01-05 13:40 GMT+08:00 jayronlou <notifications@github.com>:

> 好吧，我还以为在4.1以下的版本不能用呢，我试下，多谢了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cundong/SmartAppUpdates/issues/7#issuecomment-168904604>
> .
>



-- 
沉舟侧畔千帆过,病树前头万木春~
